# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.array(np.arange(0,9)).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [231]:
np.random.rand(1)

array([0.96514556])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [273]:
print("Random number generation (from a standard normal distribution)")
np.random.randn(5,5)

Random number generation (from a standard normal distribution)


array([[ 1.19005373,  0.24462225, -0.17245965, -1.35429694, -1.57356612],
       [-1.11701943,  0.51214495, -0.77902576,  1.27443659,  0.34469225],
       [ 0.02807061, -0.33770862,  0.81155603, -1.49013413, -0.08908414],
       [-0.50432146,  0.61451151,  0.76050461,  1.22003726,  0.73231764],
       [-1.04140124,  1.94501926, -0.84517594, -0.09942078, -0.76219464]])

#### Create the following matrix:

In [331]:
np.random.randn(10,10)

array([[-0.54481784,  1.39016068,  0.82887888, -0.8894472 ,  0.25189012,
        -0.62736899,  1.34484682,  0.65050719,  0.53585751, -1.57602488],
       [ 1.9250433 , -1.19404521,  0.31410303, -1.87473955,  0.40672772,
         0.52386138,  0.49163927,  1.42697848,  1.00749421,  1.43151247],
       [ 0.76062047,  0.30709586,  1.79019571,  2.92544909, -1.63721104,
         0.8394181 ,  0.2844309 , -0.29886871,  1.28834395, -0.06661806],
       [-0.85790148,  1.13852111, -0.29978716, -0.90106412,  1.20862142,
        -0.88886544, -0.23257255, -0.15112228,  0.27787773, -0.40749282],
       [-1.16825138,  1.30628175, -0.48587538, -0.19922806, -0.68408554,
        -0.87876138,  1.26676696, -2.75209086,  1.02210034, -0.99412848],
       [ 0.0259204 , -1.42684   ,  1.21731565,  0.40121614, -0.75245624,
         0.18856933,  0.54705901, -0.64150394, -0.24493105,  0.92864974],
       [-1.74606461,  2.21613197,  0.11302406,  0.63626452,  1.21976974,
         0.57040956, -0.94021503,  1.18226587

#### Create an array of 20 linearly spaced points between 0 and 1:

In [332]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [337]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [361]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

matrix[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [362]:
matrix[3,4]

20

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [384]:
matrix[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [391]:
matrix[4:,0:5]

array([[21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [399]:
matrix[3:,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [403]:
matrix.sum()

325

#### Get the standard deviation of the values in mat

In [404]:
matrix.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [408]:
matrix.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!